### PR TITLE
Cache Refactor + fixes / upgrade

### LINKED ISSUE #14: Cache - broken transaction caches
Certain caches currently marked 'perma cache' need a lower caching level.
For example `eth_getTransactionByHash` has a block reference and will return with (incomplete information) while still pending. Once its mined into a block the block reference is added but we've already cached the result. Also note that the block reference could change at any time due to forks.

### PR DESCRIPTION
**Pull request by tcoulter**
Many things:

* Refactor caching logic into separate strategies based on cache type (in the future, we may want to determine caching strategies directly from the RPC method rather than going from RPC method -> type -> strategy)
* Fix cache tests so that they run three different tests rather than one test three times (see comment on #14)
* Make `eth_getTransactionByHash` conditionally cache based on response (fixes #14)
* Add tests for `eth_getTransactionByHash`'s conditional caching (this required a modification to the Fixture subprovider to allow for conditional responses based on payload)

### CODE REVIEW

**Comment by tcoulter** [comment]
Oh ya, and tests pass.

**Comment by tcoulter** [comment]
Oh and one more thing: I've only fixed `eth_getTransactionByHash` for conditional caching logic. I'm sure there's more work to do for other requests.

**Comment by tcoulter** [comment]
Feel free to review if you want, but I'm going to try to get #9 in this PR tomorrow. Might require some more (and better) refactoring, not sure yet.

**Comment by tcoulter** [comment]
Added more:

* Refactor CondtionalPermaCacheStrategy to defer to the PermaCacheStrategy when there's no conditional for a request, meaning we only need to manage one strategy.
* Fixes #9 (I said #8 in my commit... c'est la vie) where any permacached request will now return a miss if the request is for a block earlier than what we cached (think, `eth_getCode` on the current block, then `eth_getCode` on the block before it). This strategy applies to all perma cached requests, even conditionals.

**Comment by tcoulter** [comment]
@kumavis I'd say this is now ready for review / merge.

**Comment by tcoulter** [comment]
* Added a few more tests for good measure
* Fixed a bug in block tag logic where the wrong value was returned if the block tag was unspecified in the request and was supposed to show up as the second parameter. Took this change to refactor that code as well, removing case statements and instead doing direct index lookups.

**Comment by kumavis** [comment]
finally getting a chance to try this out -- getting a test failure
```
# cache - getTransactionByHash for mined transaction
ok 69 did not error
ok 70 has response
ok 71 cacheProvider did see "eth_getTransactionByHash"
ok 72 cacheProvider did NOT handle "eth_getTransactionByHash"
ok 73 dataProvider did see "eth_getTransactionByHash"
ok 74 dataProvider did handle "eth_getTransactionByHash"
/Users/kumavis/dev/web3-provider-engine/subproviders/cache.js:127
  if (cached != null && requestedBlockNumber.gte(cached.blockNumber)) {
                                             ^

TypeError: requestedBlockNumber.gte is not a function
    at PermaCacheStrategy.hitCheck (/Users/kumavis/dev/web3-provider-engine/subproviders/cache.js:127:46)
    at ConditionalPermaCacheStrategy.hitCheck (/Users/kumavis/dev/web3-provider-engine/subproviders/cache.js:161:24)
    at BlockCacheProvider._handleRequest (/Users/kumavis/dev/web3-provider-engine/subproviders/cache.js:100:12)
    at null._onTimeout (/Users/kumavis/dev/web3-provider-engine/subproviders/cache.js:63:10)
    at Timer.listOnTimeout (timers.js:92:15)
npm ERR! Test failed.  See above for more details.
```
i'll explore this

**Comment by kumavis** [comment]
also - if you change somethings API (e.g. `fixtureSubprovider`) be sure to update all files that are using it

**Comment by kumavis** [comment]
* resolved error
* tests pass
* added skipCache tests

**Comment by kumavis** [comment]
nice work tim!

**Comment by kumavis** [comment]
published as 5.0.0

**Pull request merged**
