### PR TITLE
New HttpSubprovider

### PR DESCRIPTION
**Pull request by tcoulter**
Simple subprovider to wrap Web3.privders.HttpProvider objects. Makes inserting an existing web3 object (from Mist or Metamask, for instance) into the provider chain.

Here's how my app uses it:

https://gist.github.com/tcoulter/7fc48cf4a8107281ad5e

### CODE REVIEW

**Comment by kumavis** [comment]
hmm im confused i thought `be8a874` was merged. i must have messed that up.

**Comment by tcoulter** [comment]
Ya, it's weird. I'm not sure if you did or I did. I think I just removed a comma here in this PR.

**Comment by kumavis** [comment]
This is redundant with [our rpc subprovider](https://github.com/MetaMask/provider-engine/blob/master/subproviders/rpc.js). Ours is better because it doesnt trigger CORS pre-flight headers  on every request. Ours should be renamed http tho.

**Comment by tcoulter** [comment]
It's not redundant in that:

1. HttpProvider takes in a web3 provider as its input, which makes it easy to use and compatible with any web3 provider that uses that interface;
2. It can interface with previous providers built for that interface (i.e., no rewriting of the hooked web3 provider or the blockapps web3 provider)
3. Doesn't introduce another dependency (xhr) that must be bundled when using the provider engine in the browser.

If not this, allow me to edit the rpc subprovider to take in a web3 provider as input and call out to that instead.

**Comment by tcoulter** [comment]
> Ours is better because it doesnt trigger CORS pre-flight headers on every request
Because you're using the `request` module. This benefit wouldn't change in the browser. 

Reopening to force you to take a look at this again. :)

**Comment by kumavis** [comment]
ok just rename it to generically wrap web3 providers, it doesnt really have anything to do with http

**Comment by tcoulter** [comment]
Renamed. Should be ready for inclusion.

**Comment by kumavis** [comment]
:+1:

**Pull request merged**
