### PR TITLE
#218 - transpilation into the dist directory

### PR DESCRIPTION
**Pull request by yarrumretep**
possible implementation for #218 - I'm not sure if this is a good idea or not, but it did solve the issue for me of using this module with create-react-native app.  I'm using the ProviderEngine to work around the metamask filter event disconnect issue - because we are doing our own filter processing with our own FilterSubprovider, it works across network switches in meta-mask.

### CODE REVIEW

**Comment by mandys** [comment]
I ran into the same issues when I did yarn build for prod output ( using create-react-app ) and first errors were on rpc.js then rpc-cache-util.js index.js. Once I copied over the outputs from above, I was able to finish the build successfully. When would these changes make the final release ?

**Comment by kumavis** [comment]
- Added this
- removed dist from git
- added a prepublish hook to build + bundle

**Comment by borovik96** [comment]
How should I import transpiled versions of files?

**Comment by sivagopalvotigo** [comment]
installed 14.0.1 still getting same issue

**Comment by yarrumretep** [comment]
@borovik96 - transpiled versions live at `web3-provider-engine/dist/es5`.  I use imports like this in my React code:
```javascript
import ProviderEngine from 'web3-provider-engine/dist/es5'
import FilterSubprovider from 'web3-provider-engine/dist/es5/subproviders/filters.js'
import Web3Subprovider from "web3-provider-engine/dist/es5/subproviders/web3.js";
```

**Pull request closed without merging**
