### PR TITLE
Implement binary search gasEstimation

### PR DESCRIPTION
**Pull request by fabioberger**
This PR fixes Issue https://github.com/MetaMask/provider-engine/issues/80 by @kumavis 

There are a number of strange edge-cases where the true amount of gas required by a transaction is above the amount returned by running the transaction through the VM locally. Because of this, the newest version of Geth implements a binary search approach to gasEstimation (https://github.com/ethereum/go-ethereum/pull/3587).

I've encountered one of these edge-cases myself and found out that it was because the VMSubProvider still uses the simplistic gasEstimation technique, so I decided to port over the binary search implementation used by Geth.

There is a perf hit to this approach, since the VM must rerun the transaction log(gasLimit) times to measure whether it fails or not, but it guarantees that transactions won't ever fail because of gasEstimation issues.

### CODE REVIEW

**Comment by kumavis** [comment]
@fabioberger nice work! Do you have any estimates on how many runs this requires to complete?
My guess is `log(4019491)/log(2) ~= 22` but google suggests the worst case is `2*log(4019491-1)~=44`. I think binary search may be a "more correct" solution but I think we can come up with a better one by simulating with a high gas limit and then tracking the highest gas consumption during the duration of the run. That would only require a single run.

note:
we dont use `vm-subprovider` in the `./zero.js` preconfigured provider but it is used in `ethereumjs-testrpc`

**Comment by fabioberger** [comment]
@kumavis it takes 23 iterations every single time it runs. The last 11 iterations however are to hone in on the gas consumption to a degree of detail that could be considered superfluous:

```
gas:  2356194
gas:  1178097
gas:  589048.5
gas:  294524.25
gas:  147262.125
gas:  73631.0625
gas:  36815.53125
gas:  55223.296875
gas:  64427.1796875
gas:  69029.12109375
gas:  71330.091796875
gas:  70179.6064453125
gas:  69604.36376953125
gas:  69316.74243164062
gas:  69172.93176269531
gas:  69244.83709716797
gas:  69280.7897644043
gas:  69298.76609802246
gas:  69307.75426483154
gas:  69303.260181427
gas:  69301.01313972473
gas:  69299.8896188736
gas:  69299.32785844803
```

We could improve perf by 100% if we simply stop the binary search once the difference between iterations is < 1000 gas. This would mean ~12 iterations per gas estimation.

I'm not sure I understand your alternative approach, could you elaborate on that? Happy to give it a try once I understand what you mean.

**Comment by kumavis** [comment]
@fabioberger excellent observation! I think that optimization would be very nice and straight forward.

So the main problem with the current implementation is that it just reports the `gasUsed` at the end (`totalGasAllocated` - `gasRefund`). Its fairly common to see gas requirements during the processing of a transaction be higher than the final `gasUsed` amount. For example **when a contract calls another contract, it needs to set a gasLimit for the call** (just like on a tx). The unused portion is returned. So you can have a tx that in the end only uses 10k gas, but requires 1M gas to be reserved.

The way we can measure this with only a single VM run would be to run with a high gas limit, e.g. the block gas limit, and on each vm step, see what the current gas requirements are, and keep the highest observed.

**Comment by kumavis** [comment]
That said, im working on a new version of provider-engine that is even more modular, to make it easier to use whatever method the module consumer desires.

**Comment by fabioberger** [comment]
Ah I see! Very clever.

I've just updated the PR with the optimization we discussed.

It you are about to go through a big refactor, we can leave it like this for now and then switch to your alternative approach once the time is right ;)

**Comment by kumavis** [comment]
This looks good - just need to figure out why CI isnt running -- may be an s3 issue

**Comment by fabioberger** [comment]
Hm... I'm getting unrelated errors to gasEstimation when running `truffle test` against testrpc with this change to the codebase (testrpc has provider-engine as a dependency). It feels like a race-condition that might have been exposed by gasEstimation taking longer then before. Will let you know what I find.

**Comment by fabioberger** [comment]
Found this issue and fixed it!

**Comment by kumavis** [comment]
@fabioberger I don't see any existing tests for eth_estimateGas

would you be willing to create one or two?

**Comment by fabioberger** [comment]
@kumavis I've added unit tests for the binary search gasEstimation. Let me know what you think!

**Comment by kumavis** [comment]
published as `9.2.0`

**Comment by flyswatter** [comment]
This is an amazing contribution, thank you @fabioberger!!

**Comment by fabioberger** [comment]
No problem @flyswatter! Glad I could help!

**Pull request merged**
