### PR TITLE
[v16] bump ethereum-related dependencies

### PR DESCRIPTION
**Pull request by legobeat**
### Description

Targeting v16.x.

Bump ethereumjs and metamask library packages to latest preserving compatibility with Nodejs v12.
- Update `eth-rpc-errors` from `^3.0.0` to `^4.0.3`
- Update from `eth-sig-util@^1.4.2` to `@metamask/eth-sig-util@^4.0.1`
  - The remaining usage of `eth-sig-util@1` still present in lockfile comes from `ganache-core`, which is a devDependency only used for tests. 
- Update `ethereumjs-` packages
- Update `eth-json-rpc-filters` from `^4.2.1` to `~5.0.0`
  - `5.1.0` breaks node v12
- Update from `eth-json-rpc-infura@^5.1.0` to `@metamask/eth-json-rpc-infura@^6.0.0`
- Fix resolution of `ethereumjs-abi` to fetch from package registry instead of `github.com` via git+http.
- devDeps: Update from `ganache-core` to `ganache-cli`

### Related
- #471 
- #453

### CODE REVIEW

**Comment by legobeat** [comment]
@SocketSecurity ignore npm/eth-json-rpc-middleware@8.1.0

network access ok

**Comment by legobeat** [comment]
@SocketSecurity ignore npm/@ethersproject/providers@5.7.2
    @SocketSecurity ignore npm/micro-ftch@0.3.1

network access ok

**Comment by legobeat** [comment]
@SocketSecurity ignore npm/jsonify@0.0.1
    @SocketSecurity ignore npm/browser-resolve@2.0.0
    @SocketSecurity ignore npm/hash-base@3.0.4

new author ok

**Comment by legobeat** [comment]
@SocketSecurity ignore npm/v8-compile-cache@2.4.0

new author ok

**Comment by legobeat** [comment]
@SocketSecurity ignore npm/parse-asn1@5.1.7

new author ok

**Comment by legobeat** [comment]
@SocketSecurity ignore npm/execa@1.0.0
    @SocketSecurity ignore npm/ganache-cli@6.12.2

ganache update ok

**Review by Gudahtt — APPROVED** [review]
LGTM!

**Pull request merged**
