### PR TITLE
Add two methods to etherscan subprovider

### PR DESCRIPTION
**Pull request by flyswatter**
- 'eth_getBlockTransactionCountByNumber'
 - 'eth_getTransactionByHash'

Sorry I'd forgotten commas @axic

### CODE REVIEW

**Comment by axic** [comment]
As long as it works it looks good :)

**Comment by flyswatter** [comment]
Verified it works and merging!

**Comment by flyswatter** [comment]
I also bumped the semver to reflect new features, ready for an `npm publish` when you are @kumavis.

**Comment by kumavis** [comment]
published as `7.2.2`

**Pull request merged**
