### PR TITLE
Allow multiple wallets

### PR DESCRIPTION
**Pull request by cemozerr**

### CODE REVIEW

**Comment by skmgoldin** [comment]
Is it not the case that MetaMask already has a provider which allows multiple wallets? I mean, I have multiple wallets in my browser's MetaMask presently. I'm not actually familiar with this code base, but in regards to https://github.com/trufflesuite/truffle-hdwallet-provider/pull/3 it would be cleaner to require a new provider from here that already supports this.

But like I said I'm not familiar with this codebase so I could be smoking reefer.

**Comment by flyswatter** [comment]
MetaMask is able to have multiple wallets by using Hooked-Waller-Subprovider, a different, more open ended subprovider for providing accounts and signing functions.

That means this change isn't entirely necessary, but it also probably doesn't hurt. Needs a good review, but if it's solid I don't see anything wrong with it.

**Comment by alex-miller-0** [comment]
@flyswatter Is there an example of how to instantiate a `Hooked-Wallet-Subprovider` for `truffle-hdwallet-provider`? I'd like the same functionality proposed in the above linked PR of the latter repo, but I'd rather not have to change both repos.

**Comment by alex-miller-0** [comment]
Please see https://github.com/trufflesuite/truffle-hdwallet-provider/pull/5

**Comment by kumavis** [comment]
@cemozerr im closing this because its a bit old and theres not a lot of requests for this feature
the `hooked` subprovider provides lots of hooks to customize how you get available addresses, so i think this can be solved without changes to provider-engine. let me know if you think this deserves more attention

**Pull request closed without merging**
