### PR TITLE
Adding tests for etherscan

### PR DESCRIPTION
**Pull request by Ryanmtate**

### CODE REVIEW

**Comment by flyswatter** [comment]
If I remember right, these still aren't run as part of the main suite.

Do you have an opinion on that? Is it ok to add tests to the suite that are dependent on an external service?

**Comment by Ryanmtate** [comment]
I'll add tests for the main sub-providers; realize the etherscan tests may not be useful at the moment...

**Comment by Ryanmtate** [comment]
This PR also contains a file change to hooked-wallet-ethtx.js:

`const self = this`

Received: `ReferenceError: self is not defined` when calling from eth-faucet project.

//


In the future, these should be separate PRs.

**Comment by kumavis** [comment]
@Ryanmtate thanks!

**Pull request merged**
