### PR TITLE
Decrease bundle size

### PR DESCRIPTION
**Pull request by tcoulter**
Work in progress.

### CODE REVIEW

**Comment by tcoulter** [comment]
I went against your wishes and got rid of low hanging fruit: `async` and `ethereumjs-utils` from `index.js` and some subproviders. The commits above, when only including the provider engine (and no subproviders), bundle size is reduced by more than half a Mb.

Again, this is low hanging fruit. More work to do. All tests pass up until this point.

**Comment by kumavis** [comment]
relevant to https://github.com/MetaMask/provider-engine/issues/20

could you not make them class methods? they are stateless util methods, they should just live in the util dir, and that way we can reuse them

**Comment by tcoulter** [comment]
Good point. Sure.

**Comment by tcoulter** [comment]
Functions have been moved. Tests pass.

**Comment by kumavis** [comment]
L:eyes:ks g:eyes:d!

**Pull request merged**
