### PR TITLE
middleware api proposal

### PR DESCRIPTION
**Pull request by kumavis**
WIP

experimenting with a **new middleware-based api**
request payload and response obj are **plain old javascript objects**, just **edit them in place**.
The function `next(err, returnHandler)` allows the next middleware to operate.
Provide error for catastrophic abort.
Get a callback after all remaining middleware by specifying a returnHandler.

middleware looks like this

``` js
MyMiddleware.prototype.handleRequest = function(req, res, next){
  if (req.method === 'eth_getBalance') {
    res.result = '0x1234'
  }
  next()
}
```

engine config looks like this

``` js
var engine = new ProviderEngine()
engine.use(middlewareA)
engine.use(middlewareB)
```

the block tracker has been factored out of the engine

``` js
var blockTracker = new BlockTracker(provider)
blockTracker.on('block', function(block){
  console.log('BLOCK CHANGED:', '#'+block.number.toString('hex'))
})
blockTracker.start()
```

### CODE REVIEW

**Comment by tcoulter** [comment]
What objects are `req` and `res`? Payloads/result, or are they like traditional node req/res objects?

**Comment by tcoulter** [comment]
Also, how does a middleware tell the engine it has handled the request and the engine should stop passing it further? (i.e., `res.send()` in express)

**Comment by kumavis** [comment]
@tcoulter there currently is no way for the middleware to communicate that it is done. we could add that,  but this way it allows all middleware access to the request -- maybe not that useful.

**Comment by tcoulter** [comment]
It needs the equivalent of an `end` function right, like we have now? Even in express not every piece of middleware will touch a request. It depends on which handles it first.

**Comment by kumavis** [comment]
doe it need an end function? maybe but maybe not

**Comment by tcoulter** [comment]
There's gotta be a callback so middleware can be asynchronous.

**Comment by kumavis** [comment]
there is, theres the `next` callback

**Comment by tcoulter** [comment]
Sure, but after the middleware sets the `req` object, what happens next? It shouldn't go all the way through the chain if it's fully handled. For instance, in express, if your middleware handles the request, you call `req.send()` instead of `next`. You don't call `req.send()` and then send the request further down the chain.

**Comment by tcoulter** [comment]
http://stackoverflow.com/questions/33648905/after-sending-response-how-to-end-the-current-request-processing-in-node-expres

> If the current middleware does not end the request-response cycle, it must call next() to pass control to the next middleware, otherwise the request will be left hanging.
> 
> so if a middleware needs to end the request-response early, simply do not call next() but make sure that the middleware really ends the request-response by calling res.end, res.send, res.render or any method that implicitely calls res.end

We need a similar function that performs the same behavior. Currently, in the non-refactored version of the provider engine, this is `end`. Since `res` in this PR is just a plain object, it seems this functionality is being removed.

**Comment by kumavis** [comment]
> If the current middleware does not end the request-response cycle, it must call next() to pass control to the next middleware, otherwise the request will be left hanging.

I understand the short circuit behavior of `res.send()`/`end()`, but I'm not certain that we need it. we can just go all the way through the stack. performance impact will be negligible compared.

> so if a middleware needs to end the request-response early

Idk when this would be the case

**Comment by tcoulter** [comment]
It's not about performance. It's because a request is "handled" and doesn't need further handling. For instance, what if the middleware translates a `eth_sendTransaction` into a `eth_sendRawTransaction`? Or an `eth_call` gets translated down to 7 `eth_getStorageAt` requests? Or filters - you don't want that `eth_getFilterChanges` going down through the chain and being sent the server. There's no point, but even worse, it's going to cause tons of unexpected behavior.

**Comment by kumavis** [comment]
> doesn't need further handling.

this is the key thing to my apprehension --  i think middleware built for maximum reusability can't properly know if this is true or not. by removing this as an option, middleware is built for maximum reusability by default.

> For instance, what if the middleware translates a eth_sendTransaction into a eth_sendRawTransaction? 

i dont quite understand the implications here but I would handle it similar to what we do now -- trigger an additional request for `eth_sendRawTransaction` and waiting for that to resolve before calling `next()`on the `eth_sendTransaction` req

> you don't want that `eth_getFilterChanges` going down through the chain and being sent the server.

yeah this is the most relevant case I can think of -- but a simple strategy of only going to the network if there is no result in the response obj should cover most cases

**Comment by kumavis** [comment]
Hmm another possible api...

currently middleware is a fancy object:
```js
var engine = new ProviderEngine()
var middlewareA = new FancyMiddleware()
engine.use(middlewareA)
```

instead middleware could just be a function :
```js
engine.use(function(req, res, next){
  if (req.method = 'eth_getBalance') {
    res.result = '0x1234'
  }
  next()
})
```

and if you need stateful middleware you generate a closure:
```js
var cacheLayer = CacheLayer()
engine.use(cacheLayer)

function CacheLayer(){
  var cache = {}
  return function handleRequest() { ... }
}
``````

or if you want something fancy:
```js
var cacheLayer = new FancyCacheLayer()
// cacheLayer.handleRequest needs to be bound to cacheLayer
engine.use(cacheLayer.handleRequest)
``````

**Comment by tcoulter** [comment]
> this is the key thing to my apprehension -- i think middleware built for maximum reusability can't properly know if this is true or not. by removing this as an option, middleware is built for maximum reusability by default.

This is a good response that I need to think over. And t's much better than "But do we need an end function? maybe but maybe not" :)

> but a simple strategy of only going to the network if there is no result in the response obj should cover most cases

Still, I worry that "go to network" means there's some privileged data source at the end of the stack which handles requests that aren't processed anywhere else. I think coding for this data source defeats the purpose of having middleware in the first place. Instead, every piece of middleware should be considered a possible data source -- and *this* is what provides maximum flexibility. If a middleware provides the data required, the request ends. Ideally, if a request falls through then it wasn't handled by any data source, in which case produces an error.

There's prior art here and there's good reasons to short circuit in many cases. Because we can't think of a case right now that fits our context is likely the wrong reason to deviate, especially when the reasons for these changes are mostly syntactic and don't offer new functionality. 

The pretty API is a good one (like Express) but I stand by needing an end function. Especially if you want to cater to those devs.

**Comment by kumavis** [comment]
thanks @tcoulter -- our design discussions always make me challenge my assumptions and elucidate my thought process

**Comment by kumavis** [comment]
> Still, I worry that "go to network" means there's some privileged data source at the end of the stack which handles requests that aren't processed anywhere else

I see this as a natural pattern in provider-engine stacks:
- hard coded data (e.g. clientVersion)
- optimization (e.g. caching)
- local data (e.g. key mgmt -> signing txs)
- partial data source (e.g. idk maybe special block long-polling service)
- full/remaining data source (e.g. hosted node)

> privileged data source

if you mean we need to handle this last middleware specially at the engine level, I dont think so.
the middleware can inspect the response and only hit the network if no result is present and that logic would live in the middleware.

I agree that we should treat all middleware the same from the engine perspective.

> There's prior art here and there's good reasons to short circuit in many cases. Because we can't think of a case right now that fits our context is likely the wrong reason to deviate

its a fair argument.. I'll just leave off implementing `end` until we need it or enough people ask. but I'll keep it in mind and make sure if can be added on without breaking changes.

**Comment by tcoulter** [comment]
> if you mean we need to handle this last middleware specially at the engine level, I dont think so.
Nope, I agree. I was only saying that we shouldn't, in case you thought we should. 

For what it's worth, here's the provider engine stack in the TestRPC:

* request funnel - ensures only one request is processing at a time for a subset of requests
* reactive block tracker - requests the block before or after certain requests finish processing
* filters (filter suprovider)
* geth defaults - edit certain requests to have default parameters if not given, to mimick geth
* vm (vm subprovider)
* the rest of the methods the TestRPC handles (last middleware in the chain)

**Comment by kumavis** [comment]
yes! very relevant! need to make sure the model fits your usage.

**Comment by kumavis** [comment]
so nice to have tests, even if the migration is a bit heavy

**Comment by axic** [comment]
Without having read everything, two questions:
- is this to replace the current subproviders too?
- if not, why not?

**Comment by kumavis** [comment]
this does require a rewrite of the existing subproviders

**Comment by kumavis** [comment]
this is being replaced by a new module `json-rpc-engine`

**Pull request closed without merging**
