### PR TITLE
unref etherscan interval

### PR DESCRIPTION
**Pull request by mvayngrib**

### CODE REVIEW

**Comment by mvayngrib** [comment]
hm, actually this ends up breaking stuff as node.js exits before the etherscan subprovider gets to handling my requests. See the 2nd commit for the unref/re-ref unholy combo

**Comment by kumavis** [comment]
thanks/ 
I reccomend making the ref/unref a config option in the constructor

**Comment by mvayngrib** [comment]
@kumavis the issue is that this provider only does work on an interval. So if it's a config option, and the value is `{ unref: true }`, it probably won't actually work (it'll exit).

**Comment by kumavis** [comment]
@mvayngrib sorry this is super old
I bet manually calling the `.stop()` method would have solved your problem

**Pull request closed without merging**
