### PR TITLE
Add react native support

### LINKED ISSUE #110: Support React Native
Right now the `rpc-subprovider` conditionally requires the `xhr` or `request` modules depending on the context, but it does not import a react-native solution in *that* context.

If we found a react-native compatible module that exposed a `request` compatible API, we could swap it in conditionally, and support React Native very easily.

### PR DESCRIPTION
**Pull request by capkurmagati**
Use [`fetch` api](https://facebook.github.io/react-native/docs/network.html) to enable react native support.

@flyswatter PTAL.

Fixes #110

### CODE REVIEW

**Comment by flyswatter** [comment]
Thanks for the PR!

Before merge I want to see if using this isomorphic-fetch module could let your new file work in node and browser, letting us just have one RPC provider again.

**Comment by flyswatter** [comment]
How's that mobile wallet going, btw?

**Comment by flyswatter** [comment]
@capkurmagati would you check if the `rpc.js` subprovider on [this branch](https://github.com/MetaMask/provider-engine/tree/IsomorphicFetch) works on React Native for you?  It may be a method to make one `rpc.js` work on all three targets: node, browser, & react native.

**Comment by capkurmagati** [comment]
@flyswatter There was bug in my code. I just fixed that.
And the isomorphic-fetch also works after the same fix. PTAL

We are working on the mobile wallet, now it can sign and send transactions.

**Comment by flyswatter** [comment]
Ok so I think two things and then it will be merge ready:

Add the error handling back (if result.error cb(result.error).

Move this whole file over rpc.js with isomorphic-fetch, since with isomorphic-fetch it should work the same.

I partly want to do that so that when we announce it works with react-native, we don't later make people switch which subprovider they are using.

**Comment by flyswatter** [comment]
By the way, we simply added a `fetch` subprovider that you can probably use with no problem.  It's in `subproviders/fetch.js`.  I'm going to close this for now, let us know if that works for you!

**Pull request closed without merging**
